route3: rightInside.json
route1: rightInside.json
route4: rightSmal.json
currenV: 1.3
wheelbase: 0.26
route5: rightOutSide.json
ki: 0
lhd: 0.5
routeN: 0
lhd_min: 0.1
route2: midOutside.json
route0: midInside.json
FollowTopic: /vrpn_client_node/car61/pose
minV: 1.0
mode: auto
lr: 0.09
lhd_max: 0.6
kp: 4
kd: 0
maxV: 1.0